### ISSUE TITLE
REVIEW -> Modifier profil

### ISSUE THREAD

**Issue by Ga-Mikael** [WildCodeSchool/202209-orleans-php-project-labanquepostale#232]
<img width="324" alt="Capture d’écran 2023-01-30 à 15 55 36" src="https://user-images.githubusercontent.com/89526810/215512006-6a73d60b-0dc5-4890-a4ef-91ffc98bfac7.png">
Peut être ajouter un peu de padding bot pour faire le tour de l'image ?

**Comment by VioletaBD** [comment]
Done !
