### ISSUE TITLE
fix : modifier le profil style

### ISSUE THREAD

**Issue by V-Gillet** [WildCodeSchool/202209-orleans-php-project-labanquepostale#235]
"Modifier votre profil ?" 
![image](https://user-images.githubusercontent.com/100229105/215514440-a93dfa33-d6d0-4a00-967e-0be61c68c57f.png)

Je pense que vous pouvez mettre la phrase à l'affirmatif

Il manque d'espace après le champ de l'upload de l'image

Le titre de la page est en anglais "Profile"

![image](https://user-images.githubusercontent.com/100229105/215513549-a136c95b-a825-43d6-b48a-3c541a13fcf3.png)

**Comment by VioletaBD** [comment]
Done !
